# Copyright (C) 2017 Enproduktion GmbH
#
# This file is part of 3gears.
#
# 3gears is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'
services:
  mysql:
    image: mysql:5.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE
      - MYSQL_PORT
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DIRECTORY}:/var/lib/mysql
  redis:
    image: redis:2.8
  3gears-build:
    build: .
    container_name: build_3gears
    image: 3gears:latest
    command: /bin/bash
    stdin_open: true
    depends_on:
      - redis
      - mysql
    environment:
      - RAILS_ENV
    ports:
      - 3000:3000
    volumes:
      - ${GEARS_DIRECTORY}/config:/3gears/config
      - ${GEARS_DIRECTORY}/tmp:/3gears/tmp
      - ${GEARS_DIRECTORY}/db/sphinx:/3gears/db/sphinx
      - ${GEARS_DIRECTORY}/public:/3gears/public

# 3gears test
  mysqltest:
    image: mysql:5.5
    container_name: build_mysq_test
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_USER=
      - MYSQL_DATABASE=
      - MYSQL_PORT
    volumes:
      - ${MYSQL_TEST_DIRECTORY}:/var/lib/mysql
  3gears-test-build:
    build: .
    container_name: build_3gears_test
    image: 3gears:latest
    command: /bin/bash
    stdin_open: true
    depends_on:
      - redis
      - mysqltest
    environment:
      - RAILS_ENV=test
    volumes:
      - ${GEARS_DIRECTORY}:/3gears
