# Copyright (C) 2017 Enproduktion GmbH
#
# This file is part of 3gears.
#
# 3gears is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

- name: Install rsync
  apt: name=rsync state=present update_cache=yes

- name: Add user
  user: name={{ gears_user }} shell=/bin/bash

- name: Create gears directory
  file: path={{ gears_directory }} state=directory mode=0755
  become: yes
  become_user: "{{ gears_user }}"

- name: Copy 3gears
  synchronize: src=../../../.././ dest={{ gears_directory }}
  become: yes
  become_user: "{{ gears_user }}"

- name: Create tmp folder
  file: path={{ gears_directory }}/tmp state=directory mode=0755 owner={{ gears_user }} group={{ gears_user }}

- name: Chown paths
  file: path={{ gears_directory }}/{{ item }} owner={{ gears_user }} group={{ gears_user }} recurse=yes
  with_items:
    - docker
    - config
    - db
    - public
    - tmp
