# Copyright (C) 2017 Enproduktion GmbH
#
# This file is part of 3gears.
#
# 3gears is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

development:
  mysql41: 9312
  charset_table: "/, ., -, 0..9, A..Z->a..z, _, a..z, U+C0..U+DF->U+E0..U+FF, U+E0..U+FF"
  dict: keywords
  enable_star: true
  min_prefix_len: 2

test:
  mysql41: 9313
  charset_table: "/, ., -, 0..9, A..Z->a..z, _, a..z, U+C0..U+DF->U+E0..U+FF, U+E0..U+FF"
  dict: keywords
  enable_star: true
  min_prefix_len: 2

production:
  charset_table: "/, ., -, 0..9, A..Z->a..z, _, a..z, U+C0..U+DF->U+E0..U+FF, U+E0..U+FF"
  searchd_file_path: "/usr/share/3dox/sphinx"
  searchd_log_file: "/var/log/3dox-search.log"
  query_log_file: "/var/log/3dox-search-query.log"
  pid_file: "/var/run/3dox-sphinx.pid"
